services:
  godoworks:
    build: .
    container_name: godoworks-system
    ports:
      - "5173:8080" # Mapeamos tu puerto habitual 5173 al 8080 del contenedor
    environment:
      - WEBUI_SECRET_KEY=tu_clave_secreta_aqui
      - CORS_ALLOW_ORIGIN=http://192.168.5.46:5173
    volumes:
      - ./data:/app/data # Guarda la base de datos y chats aquï¿½
    restart: always